### PR TITLE
add requirements file

### PR DESCRIPTION
**Pull request by nhilton92**
Requirements file so that anyone can get started with the repo by pip installing these packages into their virtual environment 

I added the current modules for any package used in all files - Excluding standard python 3.6 packages

You can use `pip install -r --upgrade requirements.txt` from within the base directory to install these packages

Partly addresses issue in https://github.com/sfbrigade/nltweets/issues/6

### CODE REVIEW

**Comment by pahdo** [comment]
Looks good! Thanks for putting this together.

**Comment by pahdo** [comment]
Can you squash these commits when merging?

**Comment by VincentLa14** [comment]
@pahdo We can make it a setting to squash commits when merging a pull request. I think I've done that now.

**Comment by VincentLa14** [comment]
See #21

**Comment by nhilton92** [comment]
Happy to move over to Anaconda as we discussed

**Pull request closed without merging**
