### PR TITLE
Tweet cleaning and #v@

### PR DESCRIPTION
**Pull request by rileypredum**
**1. Brief Summary of what this PR accomplishes (140 characters or less. If you find trouble describing what you are doing in this length, consider breaking the PR into multiple ones.)**
cleans emojis and writes to csv

**2. Link to GitHub Issue**
https://github.com/sfbrigade/nltweets/issues/50

**3. More detailed description and other questions to address in code review**
decodes and encodes in order to remove emojis, also I removed rows that were coerced into empty strings due to that process

**4. Remember to tag reviewers!**
@pahdo thanks!

### CODE REVIEW

**Comment by pahdo** [comment]
Can you resolve the merge conflicts by doing a rebase? Let me know if you need help with that.

**Comment by frhino** [comment]
1. What is the `Enter the term you want to scrape` input asking for?
2. I get tweets after inputs, but they seem to be relating to scuba and fishes
3. The notebook breaks for me at the 6th cell starting with `# Remove the usernames`. Can you help me understand what it's doing here?

**Comment by rileypredum** [comment]
@frhino 

1. That's where you input the term you want to scrape after you specify # or @ (i.e. if you want #muniproblems it would be '#' and then'muniproblems'

2. The last time I ran it, I scraped #fish, so try running again from the top and specifying your term. I tested it and got a new output that was not the fish one.

3. What's your error? Basically in cell 4 and 5 I cleaned the encoding of the tweets to exclude emojis and special characters. Non-English words and characters are included in that. The best example I have because I got a bunch for the fish and scuba example is Japanese. This algorithm can't keep Japanese and other non-western texts unfortunately. Cell 6 drops the ones that were all non-western encoding, which is why you see the line that drop the indices of any that became empty strings after the cleaning. Hope this helps! Let me know :)

**Comment by frhino** [comment]
@rileypredum 
I started by deleting the file in data/manual.
The inputs I'm using are
```
Enter the number of tweets that you want to extract- 10
Enter which you are searching for, a hashtag (#), or a mention (@)- sfmta_muni
Enter the term you want to scrape- wait
Extracted 10 tweets with sfmta_muniwait
```
Turns out, the file generated in data/manual has 0 tweets at this point. If I leave the term field blank, I get 20 tweets, not 10. Then if I continue through the notebook, at the end I have 40 tweets, uncleaned. Let's look Wed. May be we aren't using the same environment?

**Pull request merged**
